main: com.spurposting.plugin.App
name: ObjectiveUtils
version: 0.5.20
description: Useful utilities for dealing with scoreboard objectives in Minecraft
api-version: 1.15
author: Ryan Moore

commands:
  obj:
    description: scoreboard utils
    usage: /obj <clear|list|copy|flip> <scoreboard> [startIndex] [stopIndex]
    aliases:
      objective