main: com.spurposting.plugin.App
name: FlipBoard
version: 0.1
commands:
  sbflip:
    description: flip a scoreboard
    usage: /sbflip <scoreboard> <newScoreboard>
  
  splits:
    description: list splits of a scoreboard
    usage: /splits <scoreboard>